// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using Azure.Core.Extensions;
using WebDotNetMentoringProgramApiClient;

namespace Microsoft.Extensions.Azure
{
    /// <summary> Extension methods to add <see cref="WebDotNetMentoringProgramClient"/> to client builder. </summary>
    public static partial class WebDotNetMentoringProgramClientBuilderExtensions
    {
        /// <summary> Registers a <see cref="WebDotNetMentoringProgramClient"/> instance. </summary>
        /// <param name="builder"> The builder to register with. </param>
        /// <param name="endpoint"> server parameter. </param>
        public static IAzureClientBuilder<WebDotNetMentoringProgramClient, WebDotNetMentoringProgramClientOptions> AddWebDotNetMentoringProgramClient<TBuilder>(this TBuilder builder, Uri endpoint)
        where TBuilder : IAzureClientFactoryBuilder
        {
            return builder.RegisterClientFactory<WebDotNetMentoringProgramClient, WebDotNetMentoringProgramClientOptions>((options) => new WebDotNetMentoringProgramClient(endpoint, options));
        }

        /// <summary> Registers a <see cref="WebDotNetMentoringProgramClient"/> instance. </summary>
        /// <param name="builder"> The builder to register with. </param>
        /// <param name="configuration"> The configuration values. </param>
        public static IAzureClientBuilder<WebDotNetMentoringProgramClient, WebDotNetMentoringProgramClientOptions> AddWebDotNetMentoringProgramClient<TBuilder, TConfiguration>(this TBuilder builder, TConfiguration configuration)
        where TBuilder : IAzureClientFactoryBuilderWithConfiguration<TConfiguration>
        {
            return builder.RegisterClientFactory<WebDotNetMentoringProgramClient, WebDotNetMentoringProgramClientOptions>(configuration);
        }
    }
}
